### ISSUE TITLE
Refraction Strength

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifxml#14]
Reported by - Renegade1979

"After looking at the _byoh\clutter\resources\glass.nif mesh from Skyrim's Hearthfire DLC I've realized that Unknown Float 2 in BSLightingShaderProperty is used for setting the strength of the refraction applied to a NiTriShape via SLSF1_Refraction. 
We can add SLSF1_Fire_Refraction and SLSF1_Temp_Refraction to it, so with this unknown value value set to 0 refraction doesn't work. 

Tons of modders gotta know about that :D Also it's possible to duplicate a transparent branch then add refraction shader to it."

@ttl269 or @skyfox69 can you look into this, I can provide files mentioned. 

Not too sure about the "duplicate transparent branch" comment, possibly just a workflow thing.

**Comment by jonwd7** [comment]
This was fixed in 2b63fb07ec7f6d7c481c363ed5a25654d421688a but didn't close this.
