### ISSUE TITLE
Skyrim Havok Material

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifxml#20]
Found a material not in the nif.xml in bhkCompressedMeshShape - 401067200
~\meshes\architecture\orclonghouse\orcawningpartitionb01.nif

**Comment by jonwd7** [comment]
Indeed this has been addressed with the recent decoding in #58 ...  The 2nd value in most bhk blocks is referred to as "User Data" if it doesn't have a specific use like Material ID.   In this case it is likely just an unused/garbage value.   ![](https://cdn.discordapp.com/attachments/309751208371814400/322746544438771722/unknown.png)
