### ISSUE TITLE
NiTimeController Flags and default values

### ISSUE THREAD

**Issue by jonwd7** [niftools/nifxml#45]
There are a 5th and 6th undocumented bit in Skyrim NiTimeController blocks. I do not know how early the extra bits were introduced.

The default value of the Flags is generally:

`1000101` (69) - If the effects are not marked Active and there are no sequences.
`1001000` (72) - If the effects are marked Active and there are no sequences.
`1101100` (108) - If the effects are controlled by a sequence.

Bit 5 might have something to do with the fact that in NIFs with sequences, the controllers on the actual meshes/properties use a blend Interpolator (e.g. `NiBlendFloatInterpolator`) with no keyframe data.  Changing sequences basically reroutes what interpolators the mesh/property is using.  But turning it off doesn't seem to change sequence behavior.

Bit 6, I have no idea but all Skyrim NIFs I've seen have it.  Toggling it off didn't seem to have any effect though.

So, in the nif.xml I would recommend adding something like:

```
    Bit 5 : Generally only set when sequences are present
    Bit 6 : Always seems to be set on Skyrim NIFs, unknown function
```

Or maybe we can figure out exactly what the flags are supposed to be and provide better documentation.

Also, the documentation for bits 1-2 should say:

```
Bit 1-2 : Cycle type  00=Loop 01=Reverse 10=Clamp
```

(it says "Loop" twice currently)

... and for Frequency, the default may as well be added:

```
<add name="Frequency" type="float" default="1.0">Frequency</add>
```

**Comment by neomonkeus** [comment]
Yeah having bit ranges would be so much nicer, I actually always use the look example. 
If it is true that the range of valid usable bits has been extended, then more reason to do it given that we can condition them.

**Comment by ttl269** [comment]
**Bit 5** is described in CK's Preview Scene Graph as "Is manager controlled". This bit it is set in any Controller which is subordinated to any Manager. It is usually case of `NiMultiTargetTransformController` which is direct child of `NiControllerManager` and then all controllers used in `NiControllerSequence` blocks. Good example is vanilla "meshes\weapons\boundweapons\boundswordencheffects.nif" where is a large number of various Controllers and all of them has set this bit. This bit is used in Oblivion, Fallout and Skyrim.

**Bit 6** - I have also no idea what function it has. Also tried to turn it off and didn't noticed any change of animation behavior in game. I can only confirm, that it is always set also in Fallout nifs. Oblivion don't use it.

I have made appropriate change to nif.xml - see #46.

**Comment by jonwd7** [comment]
So right after #46 was merged I found out the meaning of Bit 6 and also a Bit 7

Bit 6:  Compute Scaled Time
Bit 7:  Force Update
