### ISSUE TITLE
FO3/OB Regressions

### ISSUE THREAD

**Issue by jonwd7** [niftools/nifxml#52]
Originally discussed here:  https://github.com/niftools/nifxml/pull/51#issuecomment-205422914

The latest XML gives the following errors when scanning all FO3 meshes:

https://gist.github.com/jonwd7/390c5d88b3f64766e8f0dc301fc1f7a9

There appear to be 3 separate regressions.
## Issue 1 (Commit bbd0d5e2511e4c6f8cc31fd2e84905ff6233a9e4)

```
meshes/architecture/megaton/megatonrampturn45sml.nif
meshes/architecture/megaton/megatonrampturn90sml.nif
meshes/armor/raiderarmor01/m/glovel.nif
meshes/characters/head/headfemalefacegen.nif
meshes/dungeons/office/rubblepiles/offrubblechunka03.nif
meshes/dungeons/office/rubblepiles/offrubblechunka01.nif
meshes/dungeons/office/rubblepiles/offrubblechunka06.nif
meshes/dungeons/office/rubblepiles/offrubblechunka02.nif
meshes/dungeons/rivetcity/exterior/rcexbridge.nif
meshes/dungeons/rivetcity/exterior/rcextaircarrierback.nif
meshes/dungeons/rivetcity/exterior/rcexaircarrierfront.nif
meshes/dungeons/rivetcity/exterior/rcaircarriertower.nif
meshes/dungeons/rivetcity/exterior/rcextaircarrier01.nif
```
#### Error Text Sample:

```
"device position incorrect after block number 4 (NiTriStripsData) at 0x76f ended at 0x2490 (expected 0x9bf)"
...
"failed to load file footer"
```
## Issue 2 (Commit bbd0d5e2511e4c6f8cc31fd2e84905ff6233a9e4)

```
meshes/dungeons/office/rubblepiles/offrubblechunka04.nif
meshes/dungeons/office/rubblepiles/offrubblechunka05.nif
```
#### Error Text Sample:

```
"device position incorrect after block number 4 (NiTriStripsData) at 0x80f ended at 0xcaf (expected 0xba7)"
```
## Issue 3 (Commit b14b409d17922e9cbbb814cdcaab025ae104b711)

```
meshes/triggers/trigplayerbox01.nif 
meshes/triggers/trigplayerbox03.nif 
meshes/triggers/trigplayerbox02.nif 
meshes/triggers/trigplayerbox04.nif 
meshes/triggers/trigplayerwall01.nif
meshes/triggers/trigplayerwall02.nif
meshes/triggers/trigplayerwall04.nif
meshes/triggers/trigplayerwall03.nif
```
#### Error Text Sample:

```
"device position incorrect after block number 3 (bhkBoxShape) at 0x3b4 ended at 0x3d0 (expected 0x3d4)"
"device position incorrect after block number 4 (bhkTransformShape) at 0x3d4 ended at 0x424 (expected 0x428)"
"device position incorrect after block number 5 (bhkSimpleShapePhantom) at 0x428 ended at 0x48b (expected 0x48c)"
```
## Issue 4

```
D:/Oblivion/Data/meshes/meshes/marker_arrow.nif (4.0.0.2)
"next block does not start with a NiString"
D:/Oblivion/Data/meshes/meshes/marker_divine.nif (4.0.0.2)
"next block does not start with a NiString"
D:/Oblivion/Data/meshes/meshes/marker_radius.nif (3.3.0.13)
"next block does not start with a NiString"
D:/Oblivion/Data/meshes/meshes/marker_temple.nif (4.0.0.2)
"next block does not start with a NiString"
D:/Oblivion/Data/meshes/meshes/marker_travel.nif (4.0.0.2)
"next block does not start with a NiString"
```

**Comment by jonwd7** [comment]
Issue 1 *should* be resolved by #51 but I haven't checked yet.

I will track down the source of the other two issues if nobody else does first.

**Comment by ttl269** [comment]
### Issue 1 and 2
I have tested meshes mentioned in Issue 1 and 2 on nif.xml from #51 and everything seems ok. No errors produced in Nifskope. #51 assures taking value of `UV Sets` for Bethesda nifs only from first bit, so it allows values 0 or 1 only.
### Issue 3
It is caused by different value of `User Version 2` of all nifs in directory *meshes/triggers*, so these nifs are not considered as "Fallout 3".
*"collisionboxstatic.nif"* has `User Version 2` set to 11.
All other meshes have `User Version 2` set to 21.
**Solution 1** would be to change value of tested `User Version 2` from 34 only to range between 11 and 34 in all conditions catching Fallout 3 nifs. This would make these conditions much more complicated.
**Solution 2** would be to completely remove testing of `User Version 2` to be equal to 34 from all conditions catching Fallout 3 nifs and consider nif being "Fallout 3" only by testing `User Version` to be equal to 11 and of course `Version` to be 20.2.0.7.

**Comment by jonwd7** [comment]
@ttl269  I will look into what you are saying regarding Issue 3, but it's still definitely a regression.  From what you described it sounded as if maybe we always had the version checking wrong for those, but the issue only started in commit b14b409d17922e9cbbb814cdcaab025ae104b711.   It does not occur with the XML from 2a213ee84554ec5f3a0030771b4f2761c201a897.

Unless this is the part of the XML you are talking about.  I do see 

    <add name="Layer" type="Fallout3Layer" default="STATIC" vercond="(Version == 20.2.0.7) &amp;&amp; (User Version == 11) &amp;&amp; (User Version 2 == 34)">Sets mesh color in Fallout 3 GECK.</add>

In the HavokColFilter.  Are the conditions in these Layers the source of the issue?

**Comment by ttl269** [comment]
@jonwd7 Yes, it seems that we had bad version checking for Fallout 3. It is my fault that there is `User Vesion 2 == 34`. I didn't noticed that meshes in *triggers* directory have different `User Version 2` values.
> In the HavokColFilter. Are the conditions in these Layers the source of the issue?

No - for these meshes in *triggers* directory. It is in the HavokMaterial compound - it causes that (for example for *trigactorbox01.nif*) there is no `Material` in `bhkBoxShape`.
```xml
    <compound name="HavokMaterial">
        <add name="Material" type="OblivionHavokMaterial" vercond="(Version != 20.2.0.7) || ((Version == 20.2.0.7) &amp;&amp; (User Version != 11) &amp;&amp; (User Version != 12) &amp;&amp; (User Version 2 != 34) &amp;&amp; (User Version 2 != 83))">The material of the shape.</add><!--condition: all except Fallout 3 and Skyrim -->
        <add name="Material" type="Fallout3HavokMaterial" vercond="(Version == 20.2.0.7) &amp;&amp; (User Version == 11) &amp;&amp; (User Version 2 == 34)">The material of the shape.</add>
        <add name="Material" type="SkyrimHavokMaterial" vercond="(Version == 20.2.0.7) &amp;&amp; (User Version == 12) &amp;&amp; (User Version 2 == 83)">The material of the shape.</add>
    </compound>
```
But generally it is everywhere, where Fallout 3 nif is catched by part of condition `User Version 2 == 34`. The nifs in Fallout 3's *triggers* directory brake this condition.
I propose to remove using `User Version 2` from conditions for Fallout 3 or use `User Version 2 >= 11`.

**Comment by ttl269** [comment]
@jonwd7 Would it be possible to scan through all Oblivion, Fallout3 and Skyrim (and maybe to do this scan also on Fallout 4) nif files and get summary of all combinations of `Version`, `User Version` and `User Version 2`? After that we could create real solid conditions for catching nif from every mentioned game. Because we will need that conditions not only for this issue but it seems that also for #52.

**Comment by jonwd7** [comment]
I updated the post with Issue 4, which I didn't include previously for some reason.  I guess because I didn't confirm it was an actual regression (the point of this issue).  But I assume at some point the XML did handle those correctly as well.

@ttl269  I scanned naively by adding version + userversion + userversion2 into one integer and then adding this to a static vector to test against for the next scanned mesh.   Theoretically I should be using bitmasking/shifting to generate this integer value but I'm lazy.  I don't think any userver and userver2 combinations add up to the same number anyway.

These are just the **first found results** for each version/userver/userver2 combination.  If you would like me to generate a list of all the NIFs for each less common version for each game I can.

    D:/Oblivion/Data/meshes/meshes/architecture/anvil/anvilaltar01.nif (20.0.0.5)
    "Found Version 14000005 11 11"
    D:/Oblivion/Data/meshes/meshes/creatures/horse/bridle.nif (10.1.0.106)
    "Found Version a01006a 10 5"
    D:/Oblivion/Data/meshes/meshes/creatures/horse/horn.nif (20.0.0.4)
    "Found Version 14000004 10 11"
    D:/Oblivion/Data/meshes/meshes/creatures/horse/bridle_db.nif (20.0.0.4)
    "Found Version 14000004 11 11"
	
    D:/Fallout 3/meshes/ammo/308ammo.nif (20.2.0.7)
    "Found Version 14020007 11 34"
    D:/Fallout 3/meshes/dungeons/vaultruined/clutter/terminalinterfacer01.nif (20.2.0.7)
    "Found Version 14020007 11 26"
    D:/Fallout 3/meshes/interface/testloadanim01.nif (20.2.0.7)
    "Found Version 14020007 11 14"
    D:/Fallout 3/meshes/triggers/collisionboxstatic.nif (20.0.0.4)
    "Found Version 14000004 11 11"
    D:/Fallout 3/meshes/triggers/spelltarget.nif (20.2.0.7)
    "Found Version 14020007 11 21"
	
    D:/Skyrim/Assets/Data/meshes/actors/alduin/testalduin.nif (20.2.0.7)
    "Found Version 14020007 12 83"
    D:/Skyrim/Assets/Data/meshes/architecture/farmhouse/fern01.nif (20.2.0.7)
    "Found Version 14020007 11 32"
    D:/Skyrim/Assets/Data/meshes/weapons/1handmelee/1handsword.nif (20.2.0.7)
    "Found Version 14020007 11 34"
