### ISSUE TITLE
I'm really confused about the structure of this project

### ISSUE THREAD

**Issue by halgari** [niftools/nifxml#87]
I'm in the process of writing a native .NET parser that consumes nif.xml. I have most of the read structures ported, but at this point I'm completely confused as to what the authoritative source is for the `nif.xml` format. `nifdocsys` seems to use one (really old) format, the file in this repo uses `field` for struct members, and yet pyffi seems pinned to a older version of this doc that doesn't use `field` and instead uses `add`. 

I had leveraged `gen_niflib.py` to generate my C# code, but it seems like that code is deprecated in favor of PyFFI? At any rate, could someone tell me how these projects are structured, is the latest commit in this repo the authoritative source for nif.xml? And if so what's the authoritative source for code generation?

Thanks!

**Comment by neomonkeus** [comment]
This is authoritative source for the format description, however I think the question you are areally asking is which version should I use. 

Each project that uses the nif.xml is just at varying stages of "version" support based on contributions to the corresponding projects.
- NifSkope is probably the most aligned with the latest version of the nif.xml.
  - There are one or two additions on the develop, which haven't been released, but they are just a few enums for skyrim.
- NifDocSys has been depreciated in favour of the one provided with this project.
  - This project contains tools folder which you should probably use as reference.
  - It has what will be the replacement for nifdocsys 
    - https://github.com/niftools/nifxml/blob/master/nifdoc.py
    - https://github.com/niftools/nifxml/tree/master/tools/nifdoc
  - This tools folder also has some stuff which is useful to read through as it provide an example implementation to reading the nif.xml to into higher level object, mainly with the intent for unit testing.
- Likewise Pyffi needs some TLC. 
  - While the Blender Niftools Addon, which uses Pyffi for NIF file IO, has made a large amount of strides in keeping up with the versions of Blender, it is bottleknecked in what Games/"Nif versions" it can support as Pyffi is unable to read the current version of nif.xml, we want to move up to latest, it just will require a large rewrite to do so.
- Pyffi is an alternative to NifLib, its not intended as a replacement, it just depends on what the user wants to use.

Regarding code generation, each library is responsible for their own code generators
- While gen_niflib.py was originally part of this repo, its not really the responsibility to support code generation for ever library, so it was removed in favour of `NifLib` being the sensible location for the code generator that well generate the library.

Probably not the answer that you wanted, but I think it answer the real question you are looking to understand.

**Comment by neomonkeus** [comment]
Closing as information supplied answers original question
